version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_USER=penman
     - POSTGRES_PASSWORD=penman
     - POSTGRES_DB=penman
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10
  backend:
    image: penman/penman-backend:latest
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY_BASE=PLEASE_CHANGE_THE_SECRET_KEY
  frontend:
    image: penman/penman-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  postgres_data: